<img style="float: left; padding-right: 0px; width: 145px" src="https://upload.wikimedia.org/wikipedia/fr/thumb/e/e9/EPF_logo_2021.png/524px-EPF_logo_2021.png"> 
<br><br>


###  <div style="text-align: right">  Data Engineering - P2024 <br> <br>  <time datetime="2023-02-28">2023/02/28 </time> <br> <br> <u>Name </u>: RAPADAMNABA Robert </div>
<br> 



#   <center>  Data Manipulation </center>




#  <center><u>  Laboratory 1 - Part 1  : Basics of NumPy </u></center>
 

In [ ]:
!pip install jyquickhelper

In [1]:
from jyquickhelper import add_notebook_menu
add_notebook_menu()

## I. Getting started with NumPy

In this lab we are going to learn how to use the NumPy package. NumPy or Numerical Python, is a Python library for numerical computation. This fundamental package for scientific computing in Python allows us to build **multidimensional array** object.

You can find more details about NumPy and its function in this documentation : [Python Numpy](https://numpy.org/) 

The very first step for using Numpy is <font color='red'>to install and import it </font>; after doing that we will be able to call it and work with it.


### <div class="alert-info"> 1. Installing NumPy </div>

To install NumPy, I strongly recommend using a scientific Python distribution. If you’re looking for the full instructions for  installing NumPy on your operating system, see [Installing NumPy](https://numpy.org/install/).

In [17]:
!pip install numpy

or

If you already have Python, you can install NumPy with:

In [16]:
conda install numpy

^C

Note: you may need to restart the kernel to use updated packages.


If you don’t have Python yet, you might want to consider using [Anaconda](https://www.anaconda.com/). It’s the easiest way to get started. The good thing about getting this distribution is the fact that you don’t need to worry too much about separately installing NumPy or any of the major packages that you’ll be using for your data analyses, like pandas, Scikit-Learn, etc.

### <div class="alert-info"> 2. How to import NumPy and know the version </div>

To access NumPy and its functions import it in your Python code like this:

In [2]:
# The standard way to import NumPy is :

import numpy as np 


The imported name is shortened to <font color='red'>np</font> for better readability of code using NumPy. **This is a widely adopted convention that you should follow so that anyone working with your code can easily understand it.**

In [4]:
# After importing numpy under the name np, to know your version of numpy, type np.__version__
np.__version__

'1.24.2'

## II. Creating a NumPy Array

There are MANY ways to instantiate a NumPy array. We will cover the most common ones below. [Docs here cover more constructors](https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.array-creation.html).
- Pass in a list to the `array()` constructor
- Use the `arange` function, similar to the range function but used for NumPy arrays. Uses arguments, (**start, stop+1, step**).
- Use `linspace` to create an array of n equally spaced values. Uses arguments (**start, stop, number of items**).
- Create an array empty, full of ones or zeros, or full of any fill value. Uses argument (**shape**) in the form of a tuple.  

You can pass in `dtype` as an optional argument for any of these. This is especially useful if you want to limit memory usage for a very large array of small integers because int8 and int16 use much less space than the default int32.

### 1. Exercise 1 : Creating NumPy arrays by passing in other Python structures(such as, lists, tuples) to the `array()` constructor
As said before, the core data structure behind Numpy is the ***N-dimensional*** [Numpy Array](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.html) or [Numpy ndarray](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html). In this exercise we are going to learn how to build a basic array. Look into the documention for help. 


#### <center> a. <u>Creating 0D arrays:  scalars</u></center>

Create **two scalars** called *scalar_1* and *scalar_2* using the `array()` constructor of NumPy, one assigned 7 and the other one assigned 8. Those scalars must be arrays of **dimension 0**. Then create another scalar using the standard/usual way. The latter will be an integer variable called *scalar_3* also assigned 7.

- After doing that use the function `type()`to print the type of these 3 scalars to ensure that they are objects from the good class. What do you notice?

- Then print the first 2 scalars together with the following attibutes : 
   -  their **dimension** (i.e., the number of axes/dimensions of these arrays or the length of the shape tuple) and their **shape** (i.e., a tuple of these array dimensions), 
   -  their **size** (i.e, the total number of elements of each array. This is equal to the product of the elements of shape)
   -  the **data-type** of these arrays' elements and the **size in bytes** of each element of the array
   -  the **total bytes** consumed by the elements of the array.

In [16]:
# TO DO
scalar_1 = np.array(7)
scalar_2 = np.array(8)
scalar_3 = 7
test = [scalar_1, scalar_2]
print("type of scalar_3 is: ", type(scalar_3))
for i in test:
    print("the type, dimension, size, data type, total bytes of %s is: %s,%s, %s, %s, %s." %(i,type(i), i.ndim, i.size, i.dtype, i.nbytes))


type of scalar_3 is:  <class 'int'>
type, dimension, size, data type, total bytes of  7  is:  <class 'numpy.ndarray'> 0 1 int64 8 8
type, dimension, size, data type, total bytes of  8  is:  <class 'numpy.ndarray'> 0 1 int64 8 8


#### <center> b. <u>Creating 1D arrays:  vectors</u></center>
Now, let's create a longer array. Create **two vectors** called *vector_1* and *vector_2* whose values ​​are [1, 2, 3] and [3, 2, 1] using the `array()` constructor of NumPy. Those vectors must be of **dimension 1**. Just like before 
- print the type of these vectors to ensure that they are objects from  `<class 'numpy.ndarray'>`
- print these vectors together with the following attibutes : 
   -  their **dimension** (i.e., the number of axes/dimensions of these arrays or the length of the shape tuple) and their **shape** (i.e., a tuple of these array dimensions), 
   -  their **size** (i.e, the total number of elements of each array. This is equal to the product of the elements of shape)
   -  the **data-type** of these arrays' elements and the **size in bytes** of each element of the array
   -  the **total bytes** consumed by the elements of the array.

In [21]:
#TO DO
vector_1 = np.array([1,2,3])
vector_2 = np.array([3,2,1])
for i in (vector_1,vector_2):
    print("the type, dimension, size, data type, total bytes of %s is: %s,%s, %s, %s, %s." %(i,type(i), i.ndim, i.size, i.dtype, i.nbytes))

the dimension, size, data type, total bytes of [1 2 3] is: 1, 3, int64, 24.
the dimension, size, data type, total bytes of [3 2 1] is: 1, 3, int64, 24.


#### <center> c. <u>Creating 2D arrays:  matrices</u></center>
Now, lets create multidimensional arrays. Create **three matrices** called *matrix_1*, *matrix_2* and *matrix_3*  of dimension 3x2,  2x2, and 3x2, respectively where the rows for *matrix_1* are [1, 2], [3, 4] and [5, 6],  those for *matrix_2* are [7, 8] and [9, 0], and those for *matrix_3* consist of the lists [1, 2.0, -1],[5, 1, 3], and of the tuple (1+1j, 3., -1+2j). Those matrices must be of **dimension 2**. Just like before 
- print the type of these matrices to ensure that they are objects from  `<class 'numpy.ndarray'>`
- print these matrices together with the following attibutes : 
   -  their **dimension** (i.e., the number of axes/dimensions of these arrays or the length of the shape tuple) and their **shape** (i.e., a tuple of these array dimensions), 
   -  their **size** (i.e, the total number of elements of each array. This is equal to the product of the elements of shape)
   -  the **data-type** of these arrays' elements and the **size in bytes** of each element of the array
   -  the **total bytes** consumed by the elements of the array.

In [33]:
# TO DO
matrix_1 = np.array([[1, 2], [3, 4], [5, 6]])
matrix_2 = np.array([[7, 8],[9, 0]])
matrix_3 = np.array([[1, 2.0, -1], [5, 1, 3], [1+1j, 3.0, -1+2j]])  # note mix of tuple and lists,and types
for i in (matrix_1, matrix_2, matrix_3):
    print("the type, dimension, size, data type, total bytes of %s is: %s,%s, %s, %s, %s." %(i,type(i), i.ndim, i.size, i.dtype, i.nbytes))

the type, dimension, size, data type, total bytes of [[1 2]
 [3 4]
 [5 6]] is: <class 'numpy.ndarray'>,2, 6, int64, 48.
the type, dimension, size, data type, total bytes of [[7 8]
 [9 0]] is: <class 'numpy.ndarray'>,2, 4, int64, 32.
the type, dimension, size, data type, total bytes of [[ 1.+0.j  2.+0.j -1.+0.j]
 [ 5.+0.j  1.+0.j  3.+0.j]
 [ 1.+1.j  3.+0.j -1.+2.j]] is: <class 'numpy.ndarray'>,2, 9, complex128, 144.


### 2. Exercise 2 : Creating numpy arrays from built-in funtions
 In the previous exercise we have seen how to build a basic array by converting Python array_like Objects to NumPy Arrays using the `array`constructor. Now, we are going to learn how to use built-in functions in NumPy to create arrays from scracth. NumPy has over 40 built-in functions for creating arrays as laid out in the [Array creation routines](https://numpy.org/doc/stable/reference/routines.array-creation.html#routines-array-creation). These functions can be split into roughly three categories, based on the dimension of the array they create: 
 

    1D arrays

    2D arrays

    ndarrays
Look into the documention for help.

#### <center> a. <u> 1D array creation functions</u></center>

Create **two vectors** called *vector_3* and *vector_4* using the built-in function  [numpy.arange](https://numpy.org/doc/stable/reference/generated/numpy.arange.html#numpy.arange) and the built_in function [numpy.linspace](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html#numpy.linspace), respectively. *vector_3* contains odd numbers from 1 to 19 and *vector_4* contains 11 equally spaced samples in the closed interval [0, 1.0]  and the size of spacing between samples (the step).

- After doing that print both vectors together with their **dimension** and their **shape**. 


In [44]:
vector_3=np.arange(1,20,1)
vector_4=np.linspace(0,1.0,11)
for i in (vector_3,vector_4):
    print("%s's dimension is %s and it's shape is %s"%(i, i.ndim, i.shape))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]'s dimension is 1 and it's shape is (19,)
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]'s dimension is 1 and it's shape is (11,)


#### <center> b. <u>  2D array creation functions</u></center>
The 2D array creation functions e.g. [numpy.eye](https://numpy.org/doc/stable/reference/generated/numpy.eye.html#numpy.eye), and [numpy.diag](https://numpy.org/doc/stable/reference/generated/numpy.diag.html#numpy.diag) define properties of special matrices represented as 2D arrays.


- Create a 2-D array called *TwoD_identity_matrix* of shape (3,3) with ones on the main diagonal and zeros elsewhere using the function `numpy.eye`
- Create a 2-D array called *Upper_diagonal_identity_matrix* of shape (3,3) with ones on the first upper diagonal and zeros elsewhere using the function `numpy.eye`
- Create a 2-D array called *Lower_diagonal_identity_matrix* of shape (3,3) with ones on the first lower diagonal and zeros elsewhere using the function `numpy.eye`
- Create an array called *Diagonal_element_of_matrix3* containing the main diagonal elements of matrix_3 using the function `numpy.diag`
- Create an array called *Upper_Diagonal_element_of_matrix3* containing the first upper diagonal elements of matrix_3 using the function `numpy.diag`
- Create an array called *Lower_Diagonal_element_of_matrix3* containing the first lower diagonal elements of matrix_3 using the function `numpy.diag`
- Create an array called *New_Diagonal_of_matrix3* with the main diagonal elements of matrix_3 on the main diagonal and zeros elsewhere using the function `numpy.diag`
- After doing that print all matrices together with their **dimension** and their **shape**.
    

In [46]:

TwoD_identity_matrix=np.eye(3)


Upper_diagonal_identity_matrix=np.eye(3,k=1)


Lower_diagonal_identity_matrix=np.eye(3,k=-1)



Diagonal_element_of_matrix3=np.diag(matrix_3)


Upper_Diagonal_element_of_matrix3=np.diag(matrix_3, k=1)

Lower_Diagonal_element_of_matrix3=np.diag(matrix_3, k=-1)

New_Diagonal_of_matrix3=np.diag(Diagonal_element_of_matrix3)

for i in (TwoD_identity_matrix,Upper_diagonal_identity_matrix,Lower_diagonal_identity_matrix,Diagonal_element_of_matrix3,Upper_Diagonal_element_of_matrix3,Lower_Diagonal_element_of_matrix3,New_Diagonal_of_matrix3):
    print(i,"   ",i.ndim,"   ",i.shape)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]     2     (3, 3)
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]     2     (3, 3)
[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]     2     (3, 3)
[ 1.+0.j  1.+0.j -1.+2.j]     1     (3,)
[2.+0.j 3.+0.j]     1     (2,)
[5.+0.j 3.+0.j]     1     (2,)
[[ 1.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  1.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j -1.+2.j]]     2     (3, 3)


#### <center> c. <u>  General ndarray creation functions</u></center>
The ndarray creation functions e.g. [numpy.ones](https://numpy.org/doc/stable/reference/generated/numpy.ones.html#numpy.ones),  [numpy.zeros](https://numpy.org/doc/stable/reference/generated/numpy.zeros.html#numpy.zeros), and [random](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.random.html#numpy.random.Generator.random) define arrays based upon the desired shape. The ndarray creation functions can create arrays with any dimension by specifying how many dimensions and length along that dimension in a tuple or list.


- Create a 1-D array called *OneD_full_of_ones* of shape (5,) using the function `numpy.ones`
- Create a 2-D array called *TwoD_full_of_ones* of shape (5,3) using the function `numpy.ones`
- Create a 3-D array called *ThreeD_full_of_ones* of shape (5,3,2) using the function `numpy.ones`

- Create a 1-D array called *OneD_full_of_zeros* of shape (5,) using the function `numpy.zeros`
- Create a 2-D array called *TwoD_full_of_zeros* of shape (5,3) using the function `numpy.zeros`
- Create a 3-D array called *ThreeD_full_of_zeros* of shape (5,3,2) using the function `numpy.zeros`

- Create a 1-D array called *OneD_Random_between_zero_and_one* of shape (5,) using the function `numpy.random` and `default_rng`
- Create a 2-D array called *TwoD_Random_between_zero_and_one* of shape (5,3) using the function `numpy.random` and `default_rng`
- Create a 3-D array called *ThreeD_Random_between_zero_and_one* of shape (5,3,2) using the function `numpy.random` and `default_rng`

- After doing that print all arrays together with their **dimension** and their **shape**.


In [49]:
OneD_full_of_ones=np.ones(5)


TwoD_full_of_ones=np.ones((5,3))


ThreeD_full_of_ones=np.ones((5,3,2))


OneD_full_of_zeros=np.zeros(5)


TwoD_full_of_zeros=np.zeros((5,3))


ThreeD_full_of_zeros=np.zeros((5,3,2))


from numpy.random import default_rng

OneD_Random_between_zero_and_one= default_rng().random(5)



TwoD_Random_between_zero_and_one= default_rng().random((5,3))


ThreeD_Random_between_zero_and_one= default_rng().random((5,3,2))

for i in (OneD_full_of_ones,TwoD_full_of_ones,ThreeD_full_of_ones,OneD_full_of_zeros,TwoD_full_of_zeros,ThreeD_full_of_zeros,OneD_Random_between_zero_and_one,TwoD_Random_between_zero_and_one,ThreeD_Random_between_zero_and_one):
    print(i,"   ",i.ndim,"   ",i.shape)



[1. 1. 1. 1. 1.]     1     (5,)
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]     2     (5, 3)
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]     3     (5, 3, 2)
[0. 0. 0. 0. 0.]     1     (5,)
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]     2     (5, 3)
[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]     3     (5, 3, 2)
[0.83525602 0.42516661 0.60447417 0.72269396 0.50296472]     1     (5,)
[[0.25513321 0.52848036 0.95667394]
 [0.59834377 0.43586085 0.06472966]
 [0.3716759  0.12811882 0.1469383 ]
 [0.80612531 0.13346602 0.88009546]
 [0.69925937 0.74008629 0.04030021]]     2     (5, 3)
[[[0.13859927 0.11613254]
  [0.22575022 0.65031941]
  [0.64745227 0.91904034]]

 [[0.22711192 0.24458279]
  [0.06011471 0.38404298]
  [0.83744851 0.05

## III. Exercise 3: Basic operations with arrays

In this exercise we are going to learn how to do the basics operations with arrays. Look into the documention for help.

To do the calculations, we are going to reuse the numpy elements we created before.


### 1. Calculation on scalars
Add up, subtract, multiply and divide *scalar_1* and *scalar_2*. Only use numpy functions.

In [50]:
#Addition
scalar_add = np.add(scalar_1,scalar_2)
print("Addition :",scalar_add)

#Substraction
scalar_sub = np.subtract(scalar_1,scalar_2)
print("Substraction :",scalar_sub)

#Multiplication
scalar_mult = np.multiply(scalar_1,scalar_2)
print("Multiplication :",scalar_mult)

#Division
scalar_div = np.divide(scalar_1,scalar_2)
print("Division :",scalar_div)

Addition : 15
Substraction : -1
Multiplication : 56
Division : 0.875


### 2. Calculation on vectors
Do the same for the vectors :
Add up, subtract, multiply and divide vector_1 and vector_2. Only use numpy functions.

In [52]:
#TO DO
print("Vector 1 :",vector_1,"Vector 2 :",vector_2)

#Addition
vector_add = np.add(vector_1,vector_2)
print("Addition :",vector_add)

#Substraction
vector_sub = np.subtract(vector_1,vector_2)
print("Substraction :",vector_sub)

#Multiplication
vector_mult = np.multiply(vector_1,vector_2)
print("Multiplication :",vector_mult)

#Division
vector_div = np.divide(vector_1,vector_2)
print("Division :",vector_div)

Vector 1 : [1 2 3] Vector 2 : [3 2 1]
Addition : [4 4 4]
Substraction : [-2  0  2]
Multiplication : [3 4 3]
Division : [0.33333333 1.         3.        ]


### 3. Calculation on matrices

For the matrix, compute the sum, the difference, the multiplication and the division of *New_Diagonal_of_matrix3* an *matrix_3* and also,  using only Numpy functions, print:
 - the transpose and the inverse of matrix_3. 
 - the sum of each column of matrix_3
 - the minimum of each row of matrix_3
 - the cumulative sum along each row of matrix_3
 - the exponential of New_Diagonal_of_matrix3
 

In [63]:
#TO DO
print("Matrix 3 :\n",matrix_3,"\n New Diagonal matrix from matrix 3  :\n",New_Diagonal_of_matrix3)

#Addition
matrix_add = np.add(matrix_3,New_Diagonal_of_matrix3)
print("Addition :\n",matrix_add)

#Substraction
matrix_sub = np.subtract(matrix_3,New_Diagonal_of_matrix3)
print("Substraction :\n",matrix_sub)

#Multiplication
matrix_mult = np.multiply(matrix_3,New_Diagonal_of_matrix3)
print("Multiplication :\n",matrix_mult)

#Division
matrix_div = np.divide(matrix_3,New_Diagonal_of_matrix3)
print("Division :\n",matrix_div)

Matrix 3 :
 [[ 1.+0.j  2.+0.j -1.+0.j]
 [ 5.+0.j  1.+0.j  3.+0.j]
 [ 1.+1.j  3.+0.j -1.+2.j]] 
 New Diagonal matrix from matrix 3  :
 [[ 1.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  1.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j -1.+2.j]]
Transpose: 
 [[ 1.+0.j  5.+0.j  1.+1.j]
 [ 2.+0.j  1.+0.j  3.+0.j]
 [-1.+0.j  3.+0.j -1.+2.j]] 
Inverse: 
 [[ 0.31351351-0.68108108j  0.28108108+0.11351351j -0.3027027 +0.41621622j]
 [ 0.07027027+0.77837838j -0.17837838-0.12972973j  0.34594595-0.47567568j]
 [-0.54594595+0.87567568j -0.07567568-0.14594595j  0.38918919-0.53513514j]] 
Sum:  [7.+1.j 6.+0.j 1.+2.j] 
Minimum:  [-1.+0.j  1.+0.j -1.+2.j] 
Exponential:  [[ 2.71828183+0.j          1.        +0.j          1.        +0.j        ]
 [ 1.        +0.j          2.71828183+0.j          1.        +0.j        ]
 [ 1.        +0.j          1.        +0.j         -0.15309187+0.33451183j]]
Addition :
 [[ 2.+0.j  2.+0.j -1.+0.j]
 [ 5.+0.j  2.+0.j  3.+0.j]
 [ 1.+1.j  3.+0.j -2.+4.j]]
Substraction :
 [[ 0.+0.j  2.+0.j -1.+0.j]
 [ 5.+

/tmp/ipykernel_2730/3736361751.py:17: RuntimeWarning: divide by zero encountered in divide
  matrix_div = np.divide(matrix_3,New_Diagonal_of_matrix3)
/tmp/ipykernel_2730/3736361751.py:17: RuntimeWarning: invalid value encountered in divide
  matrix_div = np.divide(matrix_3,New_Diagonal_of_matrix3)


In [64]:
#TO DO
print("Matrix 3 :\n",matrix_3)

#Transpose
matrix_tran = np.transpose(matrix_3)
print("Transpose : \n",matrix_tran)

#Inverse
matrix_inv = np.linalg.inv(matrix_3)
print("Inverse : \n",matrix_inv)
#sum of each column of matrix_3
column_sum=np.sum(matrix_3,axis=0)
print("The sum of each column of matrix 3 is : \n",column_sum)
#min of each row of matrix_3

min_of_rows=np.min(matrix_3,axis=1)
print("The minimum of each row of matrix 3 is : \n",min_of_rows)
#the cumulative sum along each row of matrix_3
cumulative_sum_of_rows=np.cumsum(matrix_3,axis=1)
print("The cumulative sum along each row of matrix 3 is : \n",cumulative_sum_of_rows)

#the exponential of New_Diagonal_of_matrix3
print("Exponential: ",np.exp(New_Diagonal_of_matrix3))



Matrix 3 :
 [[ 1.+0.j  2.+0.j -1.+0.j]
 [ 5.+0.j  1.+0.j  3.+0.j]
 [ 1.+1.j  3.+0.j -1.+2.j]]
Transpose : 
 [[ 1.+0.j  5.+0.j  1.+1.j]
 [ 2.+0.j  1.+0.j  3.+0.j]
 [-1.+0.j  3.+0.j -1.+2.j]]
Inverse : 
 [[ 0.31351351-0.68108108j  0.28108108+0.11351351j -0.3027027 +0.41621622j]
 [ 0.07027027+0.77837838j -0.17837838-0.12972973j  0.34594595-0.47567568j]
 [-0.54594595+0.87567568j -0.07567568-0.14594595j  0.38918919-0.53513514j]]
The sum of each column of matrix 3 is : 
 [7.+1.j 6.+0.j 1.+2.j]
The minimum of each row of matrix 3 is : 
 [-1.+0.j  1.+0.j -1.+2.j]
The cumulative sum along each row of matrix 3 is : 
 [[1.+0.j 3.+0.j 2.+0.j]
 [5.+0.j 6.+0.j 9.+0.j]
 [1.+1.j 4.+1.j 3.+3.j]]
Exponential:  [[ 2.71828183+0.j          1.        +0.j          1.        +0.j        ]
 [ 1.        +0.j          2.71828183+0.j          1.        +0.j        ]
 [ 1.        +0.j          1.        +0.j         -0.15309187+0.33451183j]]


## Conclusion 
    In this first lab, you have learnt to create different types of arrays and to perform basic arithmetic operations on them. You have seen that arithmetic operators on arrays apply elementwise. A new array is created and filled with the result. Another important thing we have seen  that these arithmetic functions are working in the same way on each type of arrays and that there are also specific functions (for the matrices for example).