<img style="float: left; padding-right: 0px; width: 145px" src="https://upload.wikimedia.org/wikipedia/fr/thumb/e/e9/EPF_logo_2021.png/524px-EPF_logo_2021.png"> 
<br><br>


###  <div style="text-align: right">  Data Engineering - P2024 <br> <br>  <time datetime="2023-02-28">2023/02/28 </time> <br> <br> <u>Name </u>: RAPADAMNABA Robert </div>
<br> 



#   <center>  Data Manipulation </center>

#  <center><u>  Laboratory 1 - Part 3  : Manipulation of Ndarrays </u></center>

In this lab, we are going to learn how to use the different fonctions that can be used with Ndarrays. 

You can find the documentation on internet. The link of each function will be at the beginning of the exercise.

In [1]:
!pip install jyquickhelper

  Using cached jyquickhelper-0.4.220-py3-none-any.whl (1.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 529.7/529.7 kB 5.3 MB/s eta 0:00:00a 0:00:01
  Using cached jupyter-1.0.0-py2.py3-none-any.whl (2.7 kB)
  Using cached ipywidgets-8.0.4-py3-none-any.whl (137 kB)
  Using cached qtconsole-5.4.0-py3-none-any.whl (121 kB)
  Using cached nbconvert-7.2.9-py3-none-any.whl (274 kB)
  Using cached terminado-0.17.1-py3-none-any.whl (17 kB)
  Using cached Send2Trash-1.8.0-py3-none-any.whl (18 kB)
  Using cached argon2_cffi-21.3.0-py3-none-any.whl (14 kB)
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.0/10.0 MB 4.1 MB/s eta 0:00:0000:010:01
  Using cached prometheus_client-0.16.0-py3-none-any.whl (122 kB)
  Using cached nest_asyncio-1.5.6-py3-none-any.whl (5.2 kB)
  Using cached nbformat-5.7.3-py3-none-any.whl (78 kB)
  Using cached notebook_shim-0.2.2-py3-none-any.whl (13 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 366.7/366.7 kB

In [4]:
from jyquickhelper import add_notebook_menu
add_notebook_menu()

In [5]:
import numpy as np
import pandas as pd



### Exercise 1: The `argsort()` function

In this exercise we are going to learn how to retrieve the index of values. For this exercise, we will use vector_1

In [6]:
vector_1 = np.array([24, 27, 30, 29, 18, 14])

- Create an array that represents the rank of each item of the given array vector_1 following a decreasing schema.

Have a look on [`argsort()`function](https://numpy.org/doc/stable/reference/generated/numpy.argsort.html)

In [7]:
Q1 = np.argsort(vector_1)[::-1]
print(vector_1)
print(Q1)

[24 27 30 29 18 14]
[2 3 1 0 4 5]


- Create an array that gives back the array by decreasing number using Q1 from the previous question.

In [8]:
Q2 = vector_1[Q1]
print(Q2)

[30 29 27 24 18 14]


### Exercise 2 : The  `empty_like` and `copy` functions

In this exercise we are going to learn how to use `empty_like` and `copy` functions. To do this, we are going to use matrix_2.

In [9]:
matrix_2 =np.linspace(1,80,num=80, dtype='int8')
matrix_2=matrix_2.reshape(8,10)
matrix_2


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65, 66, 67, 68, 69, 70],
       [71, 72, 73, 74, 75, 76, 77, 78, 79, 80]], dtype=int8)

- Create an array with the same shape and type as matrix_2. 
Use the function empty_like. Look at the documentation : https://numpy.org/doc/stable/reference/generated/numpy.empty_like.html

In [10]:
array_like_matrix2 = np.empty_like(matrix_2,dtype='int8')
print("Size of matrix_2", matrix_2.size)
print("Size of the array like matrix 2 is", array_like_matrix2.size)
print(array_like_matrix2)

Size of matrix_2 80
Size of the array like matrix 2 is 80
[[ 50  86 -60  81  -1  85   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [ 53 102 100  55  52  49 100 102  45  97]
 [100  52  53  45  52  48  57  54  45  98]
 [ 48  49  56  45  52  57  48 101 102  56]
 [ 51  49  50  48  51  54   0   0   0   0]]


You can see that when you create an array this way, the function is putting random number in the array.

- Copy matrix_2 into array_like_matrix2. 

Use the function copy. Look at the documentation : 
https://numpy.org/doc/stable/reference/generated/numpy.copy.html

In [11]:
array_like_matrix2 = np.array(matrix_2,copy=True)
array_like_matrix2

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65, 66, 67, 68, 69, 70],
       [71, 72, 73, 74, 75, 76, 77, 78, 79, 80]], dtype=int8)

### Exercise 3 :Boolean indexing

In this exercise we are going to learn how to use the `where` function. To illustrate this, we are going to use vector_3.

In [12]:
vector_3 = np.array([1, 7, 3, 4, 10, 17, 14, 29, 13])
vector_3.dtype

dtype('int64')

 - Print all of the values in vector_3 that are less than 6

In [13]:
six_down= vector_3[np.where(vector_3 < 6)]
print(six_down)

[1 3 4]


- select elements in vector_3 that are divisible by 3

In [14]:
Divisible_by_3=vector_3[np.where(vector_3%3==0)]
print(Divisible_by_3)

[3]


- select elements that satisfy these 2 conditions: (vector_3 > 2) and (vector_3 < 11)

In [15]:
Two_conditions_and = vector_3[np.where((vector_3>2)&(vector_3<11))]
print(Two_conditions_and)

[ 7  3  4 10]


In [16]:
six_up1=vector_3[np.where((vector_3==6)|(vector_3>6))]
print(six_up1)

[ 7 10 17 14 29 13]


- Use of the logical operators `|` in order to return boolean values that specify whether or not the values in vector_3  are equal to or greater than 6 .

In [17]:
#or
six_up2 = np.where((vector_3==6)|(vector_3>6),True,False)
print(six_up2)

[False  True False False  True  True  True  True  True]


- Create an array that returns the indexes of the numbers between 7 and 20, 20 included and 7 excluded.

Look at the documentation of [`np.where`](https://numpy.org/doc/stable/reference/generated/numpy.where.html) 

In [18]:
indexes_by_where = np.array(np.where((vector_3>7)&(vector_3<=20)))
print("The indexes of the number between 7 and 20 are : ",indexes_by_where,indexes_by_where.dtype)

The indexes of the number between 7 and 20 are :  [[4 5 6 8]] int64


- Return the value of the number at those indexes.

In [32]:
#TO DO
array_using_indexes_by_where = np.array([vector_3[x] for x in indexes_by_where[0]])
array_using_indexes_by_where

array([10, 17, 14, 13])

- Bonus : On the image below, perform a slicing to keep only half of the image (in its center) and replace all pixels > 150 by pixels = 255

In [33]:
from scipy import misc
import matplotlib.pyplot as plt
face = misc.face(gray=True)
plt.imshow(face, cmap=plt.cm.gray)
plt.show()
face.shape

<ipython-input-33-a051ac6dc76e>:3: DeprecationWarning: scipy.misc.face has been deprecated in SciPy v1.10.0; and will be completely removed in SciPy v1.12.0. Dataset methods have moved into the scipy.datasets module. Use scipy.datasets.face instead.
  face = misc.face(gray=True)


<Figure size 640x480 with 1 Axes>

(768, 1024)

In [34]:
x, y = face.shape

# Replace all pixels > 150 by pixels = 255 using boolean indexing
zoom_face = face[x//4:3*x//4, y//4:3*y//4]
zoom_face[zoom_face > 150] = 255

# Display the final image
plt.imshow(zoom_face, cmap=plt.cm.gray)
plt.show()

<Figure size 640x480 with 1 Axes>

### Exercise 4 : Broadcasting

    In this exercise we are going to learn how to carry out an operation between an array and a single number (also called an operation between a vector and a scalar) or between arrays of two different sizes. To illustrate this, we are going to use the following arrays .


In [35]:
matrix_A = np.ones((2, 3))
scalar_B = 3
matrix_2_1_A = np.ones((2, 1))
matrix_2_2_B = np.ones((2, 2))
matrix_1_2_C = np.ones((1, 2))

- print the result of :
  - sum between matrix_A and scalar_B, 
  - sum between matrix_A and matrix_2_1_A,
  - sum between matrix_2_1_A and matrix_2_2_B
  - sum between matrix_1_2_C and matrix_2_2_B,

In [36]:
print(np.add(matrix_A,scalar_B),"\n")
print(np.add(matrix_A,matrix_2_1_A),"\n")
print(np.add(matrix_2_1_A,matrix_2_2_B),"\n")
print(np.add(matrix_1_2_C,matrix_2_2_B),"\n")

[[4. 4. 4.]
 [4. 4. 4.]] 

[[2. 2. 2.]
 [2. 2. 2.]] 

[[2. 2.]
 [2. 2.]] 

[[2. 2.]
 [2. 2.]] 



 - What happens if you try ton compute the sum of matrix_A and matrix_2_2_B?

In [37]:
print(np.add(matrix_A,matrix_2_2_B))

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

### Exercise 5 : The `shuffle` function

In this exercise we are going to learn how to use the shuffle function. To illustrate this, we are going to use the matrix student.

In [38]:
student = np.array([['student_id', 'Class', 'Name'],
              ['01', 'V', 'Debby Pramod'],
              ['02', 'V', 'Artemiy Ellie'],
              ['03', 'V', 'Baptist Kamal'],
              ['04', 'V', 'Lavanya Davide'],
              ['05', 'V', 'Fulton Antwan'],
              ['06', 'V', 'Euanthe Sandeep'],
              ['07', 'V', 'Endzela Sanda'],
              ['08', 'V', 'Victoire Waman'],
              ['09', 'V', 'Briar Nur'],
              ['10', 'V', 'Rose Lykos']])

- Take the matrix student and shuffle the array rows from 3rd to 9th.

Look at the documentation of np.random.shuffle :
https://numpy.org/doc/stable/reference/random/generated/numpy.random.shuffle.html

In [39]:
np.random.shuffle(student)
print(student)

[['10' 'V' 'Rose Lykos']
 ['09' 'V' 'Briar Nur']
 ['06' 'V' 'Euanthe Sandeep']
 ['01' 'V' 'Debby Pramod']
 ['03' 'V' 'Baptist Kamal']
 ['02' 'V' 'Artemiy Ellie']
 ['05' 'V' 'Fulton Antwan']
 ['08' 'V' 'Victoire Waman']
 ['student_id' 'Class' 'Name']
 ['07' 'V' 'Endzela Sanda']
 ['04' 'V' 'Lavanya Davide']]


### Exercise 6 : The `startswith` function

In this exercise we are going to learn how to use the `startswith` function. To illustrate this, we are going to use the matrix student2.

In [40]:
student2 =  np.array([['01', 'V', 'Debby Pramod', 30.21],
 ['02', 'V', 'Artemiy Ellie', 29.32],
 ['03', 'V', 'Baptist Kamal', 31.00],
 ['04', 'V', 'Lavanya Davide', 30.22],
 ['05', 'V', 'Fulton Antwan', 30.21],
 ['06', 'V', 'Euanthe Sandeep', 31.00],
 ['07', 'V', 'Endzela Sanda', 32.00],
 ['08', 'V', 'Victoire Waman', 29.21],
 ['09', 'E', 'Briar Nur', 30.00],
 ['10', 'V', 'Rose Lykos', 32.00]])

- Create an array with the elements starting with a "E" character.

Look at the documentation of np.char.startswith :
https://numpy.org/doc/stable/reference/generated/numpy.char.startswith.html

In [41]:
result = student2[np.where(np.char.startswith(student2,'E'))]
print(result)

['Euanthe Sandeep' 'Endzela Sanda' 'E']


- Extract all the rows to compute the student mean weight starting with the caracter "E", "D" and "F". ( Check for the type of the weight)

Look at the documentation of astype : 
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.astype.html

In [42]:
lineE = student2[np.where(np.char.startswith(student2[:,2],'E'))]
characterE = np.mean(lineE[:,3].astype(float))
print("\nTotal weight, where student name starting with E", characterE)

lineD = student2[np.where(np.char.startswith(student2[:,2],'D'))]
characterD = np.mean(lineD[:,3].astype(float))
print("\nTotal weight, where student name starting with D", characterD)

lineF = student2[np.where(np.char.startswith(student2[:,2],'F'))]
characterF = np.mean(lineF[:,3].astype(float))
print("\nTotal weight, where student name starting with F", characterF)


Total weight, where student name starting with E 31.5

Total weight, where student name starting with D 30.21

Total weight, where student name starting with F 30.21


### Exercice 7: Missing values

In this exerice, we are going to get data from a csv to an array and then to manipulate missing values. To do that, we are going to use the csv 'Iris.csv' that give information about flowers and the size of its different caracteristics. You can see more of this dataset on Kaggle : https://www.kaggle.com/datasets/saurabh00007/iriscsv

- Import the data

Look at the documentation of genfromtxt : 
https://numpy.org/doc/stable/reference/generated/numpy.genfromtxt.html

In [43]:
iris_data = np.genfromtxt('Iris.csv',delimiter=',',dtype='float',usecols=[1, 2, 3, 4],skip_header=1)
iris_data


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

- Find the number of missing values in the file

Look at the documentation of isnan : 
https://numpy.org/doc/stable/reference/generated/numpy.isnan.html

In [44]:
missingvalues = np.isnan(iris_data).sum()
print(missingvalues)

0


- Find the number of missing values in the first column 'SepalWidthCm'

In [45]:
missingvalues2 = np.isnan(iris_data[:,2]).sum()
print(missingvalues2)

0


- Find the position of all the missing values in the first column

In [46]:
missingposition = np.where(np.isnan(iris_data[:, 0]))
print(missingposition)

(array([], dtype=int64),)


### Exercise 8 : Correlation between columns

In this exercice, we are going to learn how to calculate the correlation between two columns. To do that, we are going to use an otherdataset which is 'diabetes.csv' that gives information about people having diabete. You can see more of this dataset on Kaggle : https://www.kaggle.com/datasets/saurabh00007/diabetescsv

- As the exercise before, import the dataset thanks to numpy

In [47]:
diabetes_data = np.genfromtxt('diabetes.csv', delimiter=',', dtype='float', skip_header=1)

diabetes_data


array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

- Find the correlation between Pregnncies (1st column) and BMI (5th column).

In [48]:
corr_diabete = np.corrcoef(diabetes_data[:,0], diabetes_data[:,5])
corr_diabete


array([[1.        , 0.01768309],
       [0.01768309, 1.        ]])