<img style="float: left; padding-right: 0px; width: 145px" src="https://upload.wikimedia.org/wikipedia/fr/thumb/e/e9/EPF_logo_2021.png/524px-EPF_logo_2021.png"> 
<br><br>


###  <div style="text-align: right">  Data Engineering - P2024 <br> <br>  <time datetime="2023-02-28">2023/02/28 </time> <br> <br> <u>Name </u>: RAPADAMNABA Robert </div>
<br> 



#   <center>  Data Manipulation </center>


#  <center><u>  Laboratory 1 - Part 2  : Manipulation of Ndarrays </u></center>

!pip install jyquickhelper

In [4]:
from jyquickhelper import add_notebook_menu
add_notebook_menu()

In this lab, we are going to learn how to create, manipulate and use arrays. 

You can find the documentation here: https://numpy.org/doc/stable/reference/generated/numpy.array.html

In [5]:
import numpy as np

### Exercise 1 : Indexing  (Accessing/changing specific elements)

In this exercise we are going to learn how to access/retrieve, change specific elements from an array. For this exercise, we will use the matrix 1 below

In [6]:
matrix_1=np.linspace(1,50,dtype='int8')
matrix_1=matrix_1.reshape(5,10) # returns the array with a modified shape
matrix_1


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]], dtype=int8)

- Retrieve the element in the **third row** and **fifth column** of the matrix below.

In [7]:
Q1 = matrix_1.item(2, 4)
print(Q1)


25


- Retrieve the **last element** of the **last row**.

In [8]:
Q2 = matrix_1.item(-1)
print(Q2)

50


- Retrieve the **penultimate element** of the rows and the **6th element** of the columns.

In [9]:
Q3 = matrix_1.item(-2,5)
Q3

36

### Exercise 2 : Slicing

In this exercise we are going to learn how to retrieve a part of an array. For this exercise, we will use the matrix 2.

In [10]:
matrix_2=np.linspace(1,80,num=80, dtype= 'int8')
matrix_2=matrix_2.reshape((8,10)) # returns the array with a modified shape
matrix_2

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65, 66, 67, 68, 69, 70],
       [71, 72, 73, 74, 75, 76, 77, 78, 79, 80]], dtype=int8)

- Perform a **slicing** by retrieving only the elements from the **3rd row** 

In [11]:
Q1=matrix_2[2:3]
Q1

array([[21, 22, 23, 24, 25, 26, 27, 28, 29, 30]], dtype=int8)

- Perform a **slicing** by retrieving only the elements from the **last colomn**

In [12]:
Q2=matrix_2[0:,-1:]
Q2

array([[10],
       [20],
       [30],
       [40],
       [50],
       [60],
       [70],
       [80]], dtype=int8)

In [13]:
#Or
Q2==matrix_2[:,np.shape(matrix_2)[1]-1]
Q2

array([[10],
       [20],
       [30],
       [40],
       [50],
       [60],
       [70],
       [80]], dtype=int8)

- Perform a **slicing** by retrieving the elements from the **3rd row** to the **penultimate row excluded**.

In [14]:
Q1 = matrix_2[2:np.shape(matrix_2)[0]-1]
Q1

array([[21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65, 66, 67, 68, 69, 70]], dtype=int8)

In [15]:
# Or 
Q1 = matrix_2[2:-1]
Q1

array([[21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65, 66, 67, 68, 69, 70]], dtype=int8)

- Perform a **slicing** by retrieving the elements in the **5th column** from the **5th row to the 6th row included**.

In [16]:
Q2 = matrix_2[4:6,4:5]
Q2

array([[45],
       [55]], dtype=int8)

- Perform a **slicing** from the **second row to the fourth row excluded** and from the **third column** to the **eighth column excluded** at the same time.

In [17]:
Q3 = matrix_2[1:4,2:8]
Q3

array([[13, 14, 15, 16, 17, 18],
       [23, 24, 25, 26, 27, 28],
       [33, 34, 35, 36, 37, 38]], dtype=int8)

- Perform a **slicing** by retrieving the elements in the **3rd row** from the **3rd to the 7th column included**.

In [18]:
Q4 = matrix_2[2,2:7]
Q4

array([23, 24, 25, 26, 27], dtype=int8)

### Exercise 3: Slicing

In this exercise we are going to learn how to retrieve element from an array by using the index. For this exercise, we will use the matrix 3.

In [19]:
matrix_3 = np.array([[1,2,3,4,5,6,7,8,9,10],
                    [11,12,13,14,15,16,17,18,19,20],
                    [21,22,23,24,25,26,27,28,29,30],
                    [31,32,33,34,35,36,37,38,39,40],
                    [41,42,43,44,45,46,47,48,49,50],
                    [51,52,53,54,55,56,57,58,59,60],
                    [61,62,63,64,65,66,67,68,69,70],
                    [71,72,73,74,75,76,77,78,79,80],
                    [81,82,83,84,85,86,87,88,89,90],
                    [91,92,93,94,95,96,97,98,99,100]])

- Retrieve all elements where there columns **and** rows indexes are **even**

In [20]:
Q1 = matrix_3[::2,::2]
Q1

array([[ 1,  3,  5,  7,  9],
       [21, 23, 25, 27, 29],
       [41, 43, 45, 47, 49],
       [61, 63, 65, 67, 69],
       [81, 83, 85, 87, 89]])

Note : The 0 is not mandatory in the brackets.

- Retrieve every element of the rows **with a step of 3**.

In [21]:
Q2 = matrix_3[:,::3]
Q2

array([[  1,   4,   7,  10],
       [ 11,  14,  17,  20],
       [ 21,  24,  27,  30],
       [ 31,  34,  37,  40],
       [ 41,  44,  47,  50],
       [ 51,  54,  57,  60],
       [ 61,  64,  67,  70],
       [ 71,  74,  77,  80],
       [ 81,  84,  87,  90],
       [ 91,  94,  97, 100]])

- Slicing from **the 1st to the 5th row included** and from the **6th column to the last included**. Retrieve the rows with a step of 2 and the columns with a step of 1.

In [22]:
Q3 = matrix_3[0:5:2,5::1]
Q3

array([[ 6,  7,  8,  9, 10],
       [26, 27, 28, 29, 30],
       [46, 47, 48, 49, 50]])

### Exercise 4: Changing elements

In this exercise we are going to learn how to modify elements from an array. For this exercise, we will use the vector 4.

In [23]:
vector_4 = np.arange(1,14)
print(vector_4)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13]


- Assign the **value 5** to the **index 3** of vector_4. You should get :

[ 1,  2,  3,  5,  5,  6,  7,  8,  9, 10, 11, 12, 13]

In [24]:
...
vector_4[3] = 5
print(vector_4)

[ 1  2  3  5  5  6  7  8  9 10 11 12 13]


- Assign the **value 9** to the **last index** of vector_4.

In [25]:
...
vector_4[-1] = 9
vector_4

array([ 1,  2,  3,  5,  5,  6,  7,  8,  9, 10, 11, 12,  9])

### Exercise 5: Changing elements

In this exercise we are going to learn how to modify elements from an array. For this exercise, we will use the matrix_5.

In [26]:
matrix_5 = np.array([[0,0,0,0,0], 
                    [2,2,2,2,-2], 
                    [3,3,3,3,-3], 
                    [4,4,4,4,-4], 
                    [5,6,6,6,-5]])

- Assign the **value 1** to the whole first row

In [27]:
...
matrix_5[0] = 1
matrix_5

array([[ 1,  1,  1,  1,  1],
       [ 2,  2,  2,  2, -2],
       [ 3,  3,  3,  3, -3],
       [ 4,  4,  4,  4, -4],
       [ 5,  6,  6,  6, -5]])

- Assign to the **last column increasing values ​​starting with the value 1**.

In [28]:
matrix_5[0,-1]=1
matrix_5[1,-1]=2
matrix_5[2,-1]=3
matrix_5[3,-1]=4
matrix_5[4,-1]=5
print(matrix_5)

[[1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]
 [5 6 6 6 5]]


- Assign the **value 5** to the elements in the **last row** and to the **columns going from index 1 to index 3 inclusive**.

In [29]:
matrix_5[-1,1:4]=5
print(matrix_5)

[[1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]
 [5 5 5 5 5]]


### Exercise 5: Shape Manipulation

In this exercise we are going to learn how to change the shape of an array and how to stack together different arrays. For this exercise, we will use the following matrices: matrix_6, matrix_7, and matrix_8.

In [30]:
matrix_6=np.linspace(1,12,num=12, dtype= 'int8')
matrix_6=matrix_6.reshape((3,4)) # returns the array with a modified shape
print("Matrix 6 is :\n",matrix_6)

matrix_7=np.linspace(1,18,num=9, dtype= 'int8')
matrix_7=matrix_7.reshape((3,3)) # returns the array with a modified shape
print("Matrix 7 is :\n",matrix_7)

matrix_8=np.linspace(2,12,num=6, dtype= 'int8')
matrix_8=matrix_8.reshape((2,3)) # returns the array with a modified shape
print("Matrix 8 is :\n",matrix_8)

Matrix 6 is :
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Matrix 7 is :
 [[ 1  3  5]
 [ 7  9 11]
 [13 15 18]]
Matrix 8 is :
 [[ 2  4  6]
 [ 8 10 12]]


  - Use the `ravel()` method to change matrix_6 in a flattened array (1D array)

In [31]:
Flattened_array1= matrix_6.ravel()
Flattened_array1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int8)

  - Use the `flatten()` method to change matrix_6 in a flattened array (1D array)

In [32]:
Flattened_array2=matrix_6.flatten()
Flattened_array2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int8)

  - Use the `reshape()` method to change Flattened_array2 in an array with shape (6,2)

In [33]:
Reshaped_array=Flattened_array2.reshape(6,2)
Reshaped_array

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]], dtype=int8)

- Use the swapaxes() method to interchange the two axes of the Reshaped_array.

In [35]:
Swapaxed_array=Reshaped_array.swapaxes(0,1)
Swapaxed_array

array([[ 1,  3,  5,  7,  9, 11],
       [ 2,  4,  6,  8, 10, 12]], dtype=int8)

- Use the `vstack()`, `hstack()` and `concatenate()` methods to stack matrix_6, matrix_7, and matrix_8 together along different axes if it possible.


In [44]:
print(matrix_6,"\n\n",matrix_7,"\n\n",matrix_8,"\n\n")
matrix_9=np.vstack((matrix_7,matrix_8))
print(matrix_9,"\n\n")
matrix_9=matrix_9.swapaxes(0,1)
print(matrix_9,"\n\n")
matrix_10 = np.hstack((matrix_6,matrix_9))
print(matrix_10)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

 [[ 1  3  5]
 [ 7  9 11]
 [13 15 18]] 

 [[ 2  4  6]
 [ 8 10 12]] 


[[ 1  3  5]
 [ 7  9 11]
 [13 15 18]
 [ 2  4  6]
 [ 8 10 12]] 


[[ 1  7 13  2  8]
 [ 3  9 15  4 10]
 [ 5 11 18  6 12]] 


[[ 1  2  3  4  1  7 13  2  8]
 [ 5  6  7  8  3  9 15  4 10]
 [ 9 10 11 12  5 11 18  6 12]]
