<img style="float: left; padding-right: 0px; width: 145px" src="https://upload.wikimedia.org/wikipedia/fr/thumb/e/e9/EPF_logo_2021.png/524px-EPF_logo_2021.png"> 
<br><br>


###  <div style="text-align: right">  Data Engineering - P2024 <br> <br>  <time datetime="2023-02-28">2023/02/28 </time> <br> <br> <u>Name </u>: RAPADAMNABA Robert </div>
<br> 



#   <center>  Data Manipulation </center>


#  <center><u>  Laboratory 1 - Part 2  : Manipulation of Ndarrays </u></center>

In [4]:
!pip install jyquickhelper

In [49]:
from jyquickhelper import add_notebook_menu
add_notebook_menu()

In this lab, we are going to learn how to create, manipulate and use arrays. 

You can find the documentation here: https://numpy.org/doc/stable/reference/generated/numpy.array.html

In [6]:
import numpy as np

### Exercise 1 : Indexing  (Accessing/changing specific elements)

In this exercise we are going to learn how to access/retrieve, change specific elements from an array. For this exercise, we will use the matrix 1 below

In [7]:
matrix_1=np.linspace(1,50,dtype='int8')
matrix_1=matrix_1.reshape(5,10) # returns the array with a modified shape
matrix_1

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]], dtype=int8)

- Retrieve the element in the **third row** and **fifth column** of the matrix below.

In [8]:
#TO DO
element_row3_column5 = ...
element_row3_column5

25

- Retrieve the **last element** of the **last row**.

In [9]:
#TO DO
last_element_of_last_row = ...
last_element_of_last_row

50

- Retrieve the **element**  in the **penultimate row** and the **6th column**.

In [10]:
#TO DO
element_penultimateRow_column6 = ...
element_penultimateRow_column6

36

### Exercise 2 : Slicing 1

In this exercise we are going to learn how to retrieve a part of an array. For this exercise, we will use the matrix 2.

In [11]:
matrix_2=np.linspace(1,80,num=80, dtype= 'int8')
matrix_2=matrix_2.reshape((8,10)) # returns the array with a modified shape
matrix_2

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65, 66, 67, 68, 69, 70],
       [71, 72, 73, 74, 75, 76, 77, 78, 79, 80]], dtype=int8)

- Perform a **slicing** by retrieving only the elements of the **3rd row** 

In [12]:
#TO DO
element_of_the_thirdRow=...
element_of_the_thirdRow

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30], dtype=int8)

- Perform a **slicing** by retrieving only the elements of the **last colomn**

In [13]:
#TO DO
#using shape
element_of_the_lastColumn1=...
element_of_the_lastColumn1

array([10, 20, 30, 40, 50, 60, 70, 80], dtype=int8)

In [14]:
#TO DO
#Or without using shape
element_of_the_lastColumn2=...
element_of_the_lastColumn2

array([10, 20, 30, 40, 50, 60, 70, 80], dtype=int8)

- Perform a **slicing** by retrieving the elements from the **3rd row** to the **penultimate row excluded**.

In [15]:
#TO DO
element_from_row3_to_penultimateRow_excluded1= ...
element_from_row3_to_penultimateRow_excluded1

array([[21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60]], dtype=int8)

In [16]:
#TO DO
# Or 
element_from_row3_to_penultimateRow_excluded2= ...
element_from_row3_to_penultimateRow_excluded2

array([[21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60]], dtype=int8)

- Perform a **slicing** by retrieving the elements in the **5th column** from the **5th row to the 6th row included**.

In [17]:
#TO DO
elements_column5_rows5_6 = ...
elements_column5_rows5_6

array([45, 55], dtype=int8)

- Perform a **slicing** from the **second row to the fourth row excluded** and from the **third column** to the **eighth column excluded** at the same time.

In [18]:
#TO DO
elements_Rows2_4included_Columns3_8excluded = ...
elements_Rows2_4included_Columns3_8excluded

array([[13, 14, 15, 16, 17],
       [23, 24, 25, 26, 27],
       [33, 34, 35, 36, 37]], dtype=int8)

- Perform a **slicing** by retrieving the elements in the **3rd row** from the **3rd to the 7th column included**.

In [19]:
#TO DO
elements_Row3_columns3_7included = ...
elements_Row3_columns3_7included

array([23, 24, 25, 26, 27], dtype=int8)

### Exercise 3: Slicing 2

In this exercise we are going to learn how to retrieve element from an array by using the index. For this exercise, we will use the matrix 3.

In [20]:
matrix_3=np.linspace(1,100, num=100,  dtype='int8')
matrix_3=matrix_3.reshape((10,10))
matrix_3


array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]], dtype=int8)

- Retrieve all elements for which **columns and rows indexes** are **even**

In [21]:
#TO DO
elements_with_even_indexes_forRows_Columns = ...
elements_with_even_indexes_forRows_Columns

array([[ 1,  3,  5,  7,  9],
       [21, 23, 25, 27, 29],
       [41, 43, 45, 47, 49],
       [61, 63, 65, 67, 69],
       [81, 83, 85, 87, 89]], dtype=int8)

**Note** : The 0 is not mandatory in the brackets (See the next answer).

- Retrieve every element of the rows **with a step of 3**.

In [22]:
#TO DO
AllRows_with_step_of_three= ...
AllRows_with_step_of_three

array([[  1,   4,   7,  10],
       [ 11,  14,  17,  20],
       [ 21,  24,  27,  30],
       [ 31,  34,  37,  40],
       [ 41,  44,  47,  50],
       [ 51,  54,  57,  60],
       [ 61,  64,  67,  70],
       [ 71,  74,  77,  80],
       [ 81,  84,  87,  90],
       [ 91,  94,  97, 100]], dtype=int8)

- Slicing from **the 1st to the 5th row included** and from the **6th column to the last included**. Retrieve the **rows with a step of 2** and the **columns with a step of 1**.

In [23]:
#TO DO
Elements_Rows1_5_step2_And_Columns6_last_step1= ...
Elements_Rows1_5_step2_And_Columns6_last_step1

array([[ 6,  7,  8,  9, 10],
       [26, 27, 28, 29, 30],
       [46, 47, 48, 49, 50]], dtype=int8)

### Exercise 4: Changing elements of a vector

In this exercise we are going to learn how to modify elements from an array (a vector). For this exercise, we will use the vector 4.

In [24]:
vector_4 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13])

- Assign the **value 5** to the **index 3** of vector_4. You should get :

[ 1,  2,  3,  5,  5,  6,  7,  8,  9, 10, 11, 12, 13]

In [25]:
#TO DO
...
print(vector_4)

[ 1  2  3  5  5  6  7  8  9 10 11 12 13]


- Assign the **value 9** to the **last index** of vector_4.

In [26]:
#TO DO
...
print(vector_4)

[ 1  2  3  5  5  6  7  8  9 10 11 12  9]


### Exercise 5: Changing elements of a matrix

In this exercise we are going to learn how to modify elements from an array (a matrix). For this exercise, we will use the matrix_5.

In [27]:
matrix_5 = np.array([[0,0,0,0,0], 
                    [2,2,2,2,-2], 
                    [3,3,3,3,-3], 
                    [4,4,4,4,-4], 
                    [5,6,6,6,-5]])

- Assign the **value 1** to the whole first row

In [28]:
#TO DO
...
matrix_5

array([[ 1,  1,  1,  1,  1],
       [ 2,  2,  2,  2, -2],
       [ 3,  3,  3,  3, -3],
       [ 4,  4,  4,  4, -4],
       [ 5,  6,  6,  6, -5]])

- Assign to the **last column consecutive increasing values ​​starting with the value 1**.

In [29]:
#TO DO
...
matrix_5

array([[1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4],
       [5, 6, 6, 6, 5]])

- Assign the **value 5** to the elements in the **last row** and to the **columns going from index 1 to index 3 inclusive**.

In [30]:
#TO DO
...
matrix_5

array([[1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5]])

### Exercise 6: Shape Manipulation and matrices concatenation

In this exercise we are going to learn how to change the shape of an array and how to stack together different arrays. For this exercise, we will use the following matrices: matrix_6, matrix_7, and matrix_8.

In [31]:
matrix_6=np.linspace(1,12,num=12, dtype= 'int8')
matrix_6=matrix_6.reshape((3,4)) # returns the array with a modified shape
print("Matrix 6 is :\n",matrix_6)

matrix_7=np.linspace(1,18,num=9, dtype= 'int8')
matrix_7=matrix_7.reshape((3,3)) # returns the array with a modified shape
print("Matrix 7 is :\n",matrix_7)

matrix_8=np.linspace(2,12,num=6, dtype= 'int8')
matrix_8=matrix_8.reshape((2,3)) # returns the array with a modified shape
print("Matrix 8 is :\n",matrix_8)

Matrix 6 is :
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Matrix 7 is :
 [[ 1  3  5]
 [ 7  9 11]
 [13 15 18]]
Matrix 8 is :
 [[ 2  4  6]
 [ 8 10 12]]


  - Use the `ravel()` method to change matrix_6 in a flattened array (1D array)

In [32]:
#TO DO
Flattened_matrix6_1=...
Flattened_matrix6_1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int8)

  - Use the `flatten()` method to change matrix_6 in a flattened array (1D array)

In [33]:
#TO DO
Flattened_matrix6_2=...
Flattened_matrix6_2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int8)

  - Use the `reshape()` method to change Flattened_matrix6_2 in an array with shape (6,2)

In [34]:
#TO DO
Reshaped_Flattened_matrix6_2=...
print(" the reshape matrix is :\n",Reshaped_Flattened_matrix6_2,"\n and its shape is ",Reshaped_Flattened_matrix6_2.shape) 


 the reshape matrix is :
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]] 
 and its shape is  (6, 2)


- Use the swapaxes() method to interchange the two axes of the Reshaped_Flattened_matrix6_2.

In [35]:
#TO DO
Swapaxed_array1=...
Swapaxed_array1

array([[ 1,  3,  5,  7,  9, 11],
       [ 2,  4,  6,  8, 10, 12]], dtype=int8)

In [36]:
#TO DO
#Or
Swapaxed_array2=...
Swapaxed_array2

array([[ 1,  3,  5,  7,  9, 11],
       [ 2,  4,  6,  8, 10, 12]], dtype=int8)

- Use the `vstack()`, `hstack()` and `concatenate()` methods to stack matrix_6, matrix_7, and matrix_8 together along different axes if it possible.


### Exercise 7: Other interesting functions to be explored

These interesting methods could be aslo explored: <br><br>
    - `dstack` : Stack arrays in sequence depth wise (along third dimension).<br><br>
    - `array_split`: Split an array into multiple sub-arrays of equal or near-equal size.<br><br>
    - `split` :  Split array into a list of multiple sub-arrays of equal size.<br><br>
    - `hsplit` : Split array into multiple sub-arrays horizontally (column wise).<br><br>
    - `vsplit` : Split array into multiple sub-arrays vertically (row wise).<br><br>
    - `dsplit` : Split array into multiple sub-arrays along the 3rd axis (depth).<br><br>


### Conclusion 
    In this second notebook, you have learnt to use indexing/slicing and many built-in functions to manipulate Numpy arrays.