<img style="float: left; padding-right: 0px; width: 145px" src="https://upload.wikimedia.org/wikipedia/fr/thumb/e/e9/EPF_logo_2021.png/524px-EPF_logo_2021.png"> 
<br><br>


###  <div style="text-align: right">  Data Engineering - P2024 <br> <br>  <time datetime="2023-02-28">2023/02/28 </time> <br> <br> <u>Name </u>: RAPADAMNABA Robert </div>
<br> 



#   <center>  Data Manipulation </center>




#  <center><u>  Laboratory 1 - Part 1  : Basics of NumPy </u></center>
 

In [ ]:
!pip install jyquickhelper

In [1]:
from jyquickhelper import add_notebook_menu
add_notebook_menu()

## I. Getting started with NumPy

In this lab we are going to learn how to use the NumPy package. NumPy or Numerical Python, is a Python library for numerical computation. This fundamental package for scientific computing in Python allows us to build **multidimensional array** object.

You can find more details about NumPy and its function in this documentation : [Python Numpy](https://numpy.org/) 

The very first step for using Numpy is <font color='red'>to install and import it </font>; after doing that we will be able to call it and work with it.


### <div class="alert-info"> 1. Installing NumPy </div>

To install NumPy, I strongly recommend using a scientific Python distribution. If you’re looking for the full instructions for  installing NumPy on your operating system, see [Installing NumPy](https://numpy.org/install/).

In [17]:
!pip install numpy

or

If you already have Python, you can install NumPy with:

In [3]:
conda install numpy

\ 
Note: you may need to restart the kernel to use updated packages.


If you don’t have Python yet, you might want to consider using [Anaconda](https://www.anaconda.com/). It’s the easiest way to get started. The good thing about getting this distribution is the fact that you don’t need to worry too much about separately installing NumPy or any of the major packages that you’ll be using for your data analyses, like pandas, Scikit-Learn, etc.

### <div class="alert-info"> 2. How to import NumPy and know the version </div>

To access NumPy and its functions import it in your Python code like this:

In [2]:
# The standard way to import NumPy is :

import numpy as np


The imported name is shortened to <font color='red'>np</font> for better readability of code using NumPy. **This is a widely adopted convention that you should follow so that anyone working with your code can easily understand it.**

In [3]:
# After importing numpy under the name np, to know your version of numpy, type np.__version__
np.__version__

'1.24.2'

## II. Creating a NumPy Array

There are MANY ways to instantiate a NumPy array. We will cover the most common ones below. [Docs here cover more constructors](https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.array-creation.html).
- Pass in a list to the `array()` constructor
- Use the `arange` function, similar to the range function but used for NumPy arrays. Uses arguments, (**start, stop+1, step**).
- Use `linspace` to create an array of n equally spaced values. Uses arguments (**start, stop, number of items**).
- Create an array empty, full of ones or zeros, or full of any fill value. Uses argument (**shape**) in the form of a tuple.  

You can pass in `dtype` as an optional argument for any of these. This is especially useful if you want to limit memory usage for a very large array of small integers because int8 and int16 use much less space than the default int32.

### 1. Exercise 1 : Creating NumPy arrays by passing in other Python structures(such as, lists, tuples) to the `array()` constructor
As said before, the core data structure behind Numpy is the ***N-dimensional*** [Numpy Array](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.html) or [Numpy ndarray](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html). In this exercise we are going to learn how to build a basic array. Look into the documention for help. 


#### <center> a. <u>Creating 0D arrays:  scalars</u></center>

Create **two scalars** called *scalar_1* and *scalar_2* using the `array()` constructor of NumPy, one assigned 7 and the other one assigned 8. Those scalars must be arrays of **dimension 0**. Then create another scalar using the standard/usual way. The latter will be an integer variable called *scalar_3* also assigned 7.

- After doing that use the function `type()`to print the type of these 3 scalars to ensure that they are objects from the good class. What do you notice?

- Then print the first 2 scalars together with the following attibutes : 
   -  their **dimension** (i.e., the number of axes/dimensions of these arrays or the length of the shape tuple) and their **shape** (i.e., a tuple of these array dimensions), 
   -  their **size** (i.e, the total number of elements of each array. This is equal to the product of the elements of shape)
   -  the **data-type** of these arrays' elements and the **size in bytes** of each element of the array
   -  the **total bytes** consumed by the elements of the array.

In [4]:
#TO DO
scalar_1 = np.array(7)
scalar_2 = np.array(8)
scalar_3=7

#The type() function allows to print the type of these scalars 
print("Scalar 1 is ",scalar_1, " and it is from ",type(scalar_1),".")
print("Scalar 2 is ",scalar_2, " and it is from ",type(scalar_2),".")
print("Scalar 3 is ",scalar_3, " and it is from ",type(scalar_3),".")

#The attibutes ndim and shape allow to print the dimensions and the shapes of the arrays, respectively.
print("Scalar 1 is ",scalar_1,"; its shape is :", scalar_1.shape, "; its dimension is :", scalar_1.ndim,".")
print("Scalar 2 is ",scalar_2,"; its shape is :", scalar_2.shape, "; its dimension is :", scalar_2.ndim,".")

#The dimensions of an array is also the length of the shape tuple. Therefore ndim can be printed using this information.
print("Comparison between length of tuple and ndim ",len(scalar_1.shape)== scalar_1.ndim,".")

#The attibute size  allows to print the number of elements  of the arrays.
print("Scalar 1 is ",scalar_1,"; its size is :", scalar_1.size,".")
print("Scalar 2 is ",scalar_2,"; its size is :", scalar_2.size,".")

#The attibutes dtype, and itemsize allow to print the data-type of the arrays' elements, 
# and the length of one array element in bytes, respectively. 
print("Scalar 1 is ",scalar_1,"; its elements are of type :", scalar_1.dtype, "; the size in bytes of each element of the array is :", scalar_1.itemsize,".")
print("Scalar 2 is ",scalar_2,"; its elements are of type :", scalar_2.dtype, "; the size in bytes of each element of the array is :", scalar_2.itemsize,".")

# The attribute nbytes allows to print the total bytes consumed by the elements of the arrays.
print("Scalar 1 is ",scalar_1,"and the total bytes consumed by the elements of the array is:", scalar_1.nbytes, ".")
print("Scalar 2 is ",scalar_2,"and the total bytes consumed by the elements of the array is :", scalar_2.nbytes,".")

Scalar 1 is  7  and it is from  <class 'numpy.ndarray'> .
Scalar 2 is  8  and it is from  <class 'numpy.ndarray'> .
Scalar 3 is  7  and it is from  <class 'int'> .
Scalar 1 is  7 ; its shape is : () ; its dimension is : 0 .
Scalar 2 is  8 ; its shape is : () ; its dimension is : 0 .
Comparison between length of tuple and ndim  True .
Scalar 1 is  7 ; its size is : 1 .
Scalar 2 is  8 ; its size is : 1 .
Scalar 1 is  7 ; its elements are of type : int64 ; the size in bytes of each element of the array is : 8 .
Scalar 2 is  8 ; its elements are of type : int64 ; the size in bytes of each element of the array is : 8 .
Scalar 1 is  7 and the total bytes consumed by the elements of the array is: 8 .
Scalar 2 is  8 and the total bytes consumed by the elements of the array is : 8 .


<div class="alert-danger">
     <b><u>Note</u>:<br>
    -  </b> The variables <i>scalar_1</i> and <i>scalar_2</i> are objects from the class "<b>ndarray</b>" with values array(7) and array(8) respectively, while <i>scalar_3</i> which is an integer containing the value 7 is an object instantiated from the class "<b>int</b>".</div> <br>

<div class="alert-danger"> 
    -  Here we can see that the shape is only '( )' because our array has a dimension of 0.</div>

#### <center> b. <u>Creating 1D arrays:  vectors</u></center>
Now, let's create a longer array. Create **two vectors** called *vector_1* and *vector_2* whose values ​​are [1, 2, 3] and [3, 2, 1] using the `array()` constructor of NumPy. Those vectors must be of **dimension 1**. Just like before 
- print the type of these vectors to ensure that they are objects from  `<class 'numpy.ndarray'>`
- print these vectors together with the following attibutes : 
   -  their **dimension** (i.e., the number of axes/dimensions of these arrays or the length of the shape tuple) and their **shape** (i.e., a tuple of these array dimensions), 
   -  their **size** (i.e, the total number of elements of each array. This is equal to the product of the elements of shape)
   -  the **data-type** of these arrays' elements and the **size in bytes** of each element of the array
   -  the **total bytes** consumed by the elements of the array.

In [131]:
#TO DO
vector_1 = np.array([1,2,3])
vector_2 = np.array([3,2,1])

#The type() function allows to print the type 
print("Vector 1 is ",vector_1, " and it is from ",type(vector_1),".")
print("Vector 2 is ",vector_2, " and it is from ",type(vector_2),".")
#The attibutes ndim and shape allow to print the dimensions and the shapes of the arrays, respectively.
print("Vector 1 is ",vector_1,"; its shape is :", vector_1.shape, "; its dimension is :", vector_1.ndim,".")
print("Vector 2 is ",vector_2,"; its shape is :", vector_2.shape, "; its dimension is :", vector_2.ndim,".")
#The dimensions of an array is also the length of the shape tuple. Therefore ndim can be printed using this information.
print("Comparison between length of tuple and ndim ",len(vector_1.shape)== vector_1.ndim,".")

#The attibute size  allows to print the number of elements  of the arrays.
print("Vector 1 is ",vector_1,"; its size is :", vector_1.size,".")
print("Vector 2 is ",vector_2,"; its size is :", vector_2.size,".")
#The attibutes dtype, and itemsize allow to print the data-type of the arrays' elements, 
# and the length of one array element in bytes, respectively. 
print("Vector 1 is ",vector_1,"; its elements are of type :", vector_1.dtype, "; the size in bytes of each element of the array is :", vector_1.itemsize,".")
print("Vector 2 is ",vector_2,"; its elements are of type :", vector_2.dtype, "; the size in bytes of each element of the array is :", vector_2.itemsize,".")
# The attribute nbytes allows to print the total bytes consumed by the elements of the arrays.
print("Vector 1 is ",vector_1,"and the total bytes consumed by the elements of the array is:", vector_1.nbytes, ".")
print("Vector 2 is ",vector_2,"and the total bytes consumed by the elements of the array is :", vector_2.nbytes,".")

Vector 1 is  [1 2 3]  and it is from  <class 'numpy.ndarray'> .
Vector 2 is  [3 2 1]  and it is from  <class 'numpy.ndarray'> .
Vector 1 is  [1 2 3] ; its shape is : (3,) ; its dimension is : 1 .
Vector 2 is  [3 2 1] ; its shape is : (3,) ; its dimension is : 1 .
Comparison between length of tuple and ndim  True .
Vector 1 is  [1 2 3] ; its size is : 3 .
Vector 2 is  [3 2 1] ; its size is : 3 .
Vector 1 is  [1 2 3] ; its elements are of type : int32 ; the size in bytes of each element of the array is : 4 .
Vector 2 is  [3 2 1] ; its elements are of type : int32 ; the size in bytes of each element of the array is : 4 .
Vector 1 is  [1 2 3] and the total bytes consumed by the elements of the array is: 12 .
Vector 2 is  [3 2 1] and the total bytes consumed by the elements of the array is : 12 .


<div class="alert-danger"> Here, the shape is '(3, )'. This means that there is 3 columns. There is nothing after the coma because it's only one dimentional, so their is only one line.</div>

#### <center> c. <u>Creating 2D arrays:  matrices</u></center>
Now, lets create multidimensional arrays. Create **three matrices** called *matrix_1*, *matrix_2* and *matrix_3*  of dimension 3x2,  2x2, and 3x2, respectively where the rows for *matrix_1* are [1, 2], [3, 4] and [5, 6],  those for *matrix_2* are [7, 8] and [9, 0], and those for *matrix_3* consist of the lists [1, 2.0, -1],[5, 1, 3], and of the tuple (1+1j, 3., -1+2j). Those matrices must be of **dimension 2**. Just like before 
- print the type of these matrices to ensure that they are objects from  `<class 'numpy.ndarray'>`
- print these matrices together with the following attibutes : 
   -  their **dimension** (i.e., the number of axes/dimensions of these arrays or the length of the shape tuple) and their **shape** (i.e., a tuple of these array dimensions), 
   -  their **size** (i.e, the total number of elements of each array. This is equal to the product of the elements of shape)
   -  the **data-type** of these arrays' elements and the **size in bytes** of each element of the array
   -  the **total bytes** consumed by the elements of the array.

In [132]:
#TO DO
matrix_1 = np.array([[1,2],[3,4],[5,6]])
matrix_2 = np.array([[7,8],[9,0]])
matrix_3=np.array([[1,2.0,-1],[5,1,3],(1+1j,3.,-1+2j)])# note mix of tuple and lists,and types
#The type() function allows to print the type 
print("Matrix 1 is \n",matrix_1, "\n and it is from ",type(matrix_1),".")
print("Matrix 2 is \n",matrix_2, "\n and it is from ",type(matrix_2),".")
print("Matrix 3 is \n",matrix_3, "\n and it is from ",type(matrix_3),".")
#The attibutes ndim and shape allow to print the dimensions and the shapes of the arrays, respectively.
print("Matrix 1 is \n",matrix_1,";\n its shape is :", matrix_1.shape, "; its dimension is :", matrix_1.ndim,".")
print("Matrix 2 is \n",matrix_2,";\n its shape is :", matrix_2.shape, "; its dimension is :", matrix_2.ndim,".")
print("Matrix 3 is \n",matrix_3,";\n its shape is :", matrix_3.shape, "; its dimension is :", matrix_3.ndim,".")
#The dimensions of an array is also the length of the shape tuple. Therefore ndim can be printed using this information.
print("Comparison between length of tuple and ndim ",len(matrix_1.shape)== matrix_1.ndim,".")

#The attibute size  allows to print the number of elements  of the arrays.
print("Matrix 1 is \n",matrix_1,";\n its size is :", matrix_1.size,".")
print("Matrix 2 is \n",matrix_2,";\n its size is :", matrix_2.size,".")
print("Matrix 3 is \n",matrix_3,";\n its size is :", matrix_3.size,".")
#The attibutes dtype, and itemsize allow to print the data-type of the arrays' elements, 
# and the length of one array element in bytes, respectively. 
print("Matrix 1 is \n",matrix_1,";\n its elements are of type :", matrix_1.dtype, "; the size in bytes of each element of the array is :", matrix_1.itemsize,".")
print("Matrix 2 is \n",matrix_2,";\n its elements are of type :", matrix_2.dtype, "; the size in bytes of each element of the array is :", matrix_2.itemsize,".")
print("Matrix 3 is \n",matrix_3,";\n its elements are of type :", matrix_3.dtype, "; the size in bytes of each element of the array is :", matrix_3.itemsize,".")
# The attribute nbytes allows to print the total bytes consumed by the elements of the arrays.
print("Matrix 1 is \n",matrix_1,"\n and the total bytes consumed by the elements of the array is:", matrix_1.nbytes,".")
print("Matrix 2 is \n",matrix_2,"\n and the total bytes consumed by the elements of the array is :", matrix_2.nbytes,".")
print("Matrix 2 is \n",matrix_3,"\n and the total bytes consumed by the elements of the array is :", matrix_3.nbytes,".")

Matrix 1 is 
 [[1 2]
 [3 4]
 [5 6]] 
 and it is from  <class 'numpy.ndarray'> .
Matrix 2 is 
 [[7 8]
 [9 0]] 
 and it is from  <class 'numpy.ndarray'> .
Matrix 3 is 
 [[ 1.+0.j  2.+0.j -1.+0.j]
 [ 5.+0.j  1.+0.j  3.+0.j]
 [ 1.+1.j  3.+0.j -1.+2.j]] 
 and it is from  <class 'numpy.ndarray'> .
Matrix 1 is 
 [[1 2]
 [3 4]
 [5 6]] ;
 its shape is : (3, 2) ; its dimension is : 2 .
Matrix 2 is 
 [[7 8]
 [9 0]] ;
 its shape is : (2, 2) ; its dimension is : 2 .
Matrix 3 is 
 [[ 1.+0.j  2.+0.j -1.+0.j]
 [ 5.+0.j  1.+0.j  3.+0.j]
 [ 1.+1.j  3.+0.j -1.+2.j]] ;
 its shape is : (3, 3) ; its dimension is : 2 .
Comparison between length of tuple and ndim  True .
Matrix 1 is 
 [[1 2]
 [3 4]
 [5 6]] ;
 its size is : 6 .
Matrix 2 is 
 [[7 8]
 [9 0]] ;
 its size is : 4 .
Matrix 3 is 
 [[ 1.+0.j  2.+0.j -1.+0.j]
 [ 5.+0.j  1.+0.j  3.+0.j]
 [ 1.+1.j  3.+0.j -1.+2.j]] ;
 its size is : 9 .
Matrix 1 is 
 [[1 2]
 [3 4]
 [5 6]] ;
 its elements are of type : int32 ; the size in bytes of each element of the array

<div class="alert-danger"> The shapes (n, m) tell us that there is n rows and m columns.</div>

### 2. Exercise 2 : Creating numpy arrays from built-in funtions
 In the previous exercise we have seen how to build a basic array by converting Python array_like Objects to NumPy Arrays using the `array`constructor. Now, we are going to learn how to use built-in functions in NumPy to create arrays from scracth. NumPy has over 40 built-in functions for creating arrays as laid out in the [Array creation routines](https://numpy.org/doc/stable/reference/routines.array-creation.html#routines-array-creation). These functions can be split into roughly three categories, based on the dimension of the array they create: 
 

    1D arrays

    2D arrays

    ndarrays
Look into the documention for help.

#### <center> a. <u> 1D array creation functions</u></center>

Create **two vectors** called *vector_3* and *vector_4* using the built-in function  [numpy.arange](https://numpy.org/doc/stable/reference/generated/numpy.arange.html#numpy.arange) and the built_in function [numpy.linspace](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html#numpy.linspace), respectively. *vector_3* contains odd numbers from 1 to 19 and *vector_4* contains 11 equally spaced samples in the closed interval [0, 1.0]  and the size of spacing between samples (the step).

- After doing that print both vectors together with their **dimension** and their **shape**. 


In [133]:
# useful to evaluate function at lots of points

In [134]:
#`arange(start, stop, step)` allows to generate values  within the half-open interval [start, stop), with spacing between values given by step.
vector_3=np.arange(1,20,2)
print("Vector 3 is the odd numbers from 1 to 19:",vector_3)
print("The dimension of Vector 3 is :", vector_3.ndim, "and its shape is :", vector_3.shape)

#linspace(start, stop, num=11, endpoint=True) allows to generate num equally spaced samples in the closed interval [start, stop] 
# or the half-open interval [start, stop) (depending on whether endpoint is True or False).
vector_4=np.linspace(0, 1.0, num=11)
print("Vector 4 is the odd numbers from 1 to 19:",vector_4)
print("The dimension of Vector 4 is :", vector_4.ndim, "and its shape is :", vector_4.shape)

Vector 3 is the odd numbers from 1 to 19: [ 1  3  5  7  9 11 13 15 17 19]
The dimension of Vector 3 is : 1 and its shape is : (10,)
Vector 4 is the odd numbers from 1 to 19: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
The dimension of Vector 4 is : 1 and its shape is : (11,)


<div class="alert-danger"> The advantage of the constructor `linspace(start, stop, num=11, endpoint=True)` is that you guarantee the number of elements and the starting and end point. The previous constructor `arange(start, stop, step)` will not include the value stop.</div>

#### <center> b. <u>  2D array creation functions</u></center>
The 2D array creation functions e.g. [numpy.eye](https://numpy.org/doc/stable/reference/generated/numpy.eye.html#numpy.eye), and [numpy.diag](https://numpy.org/doc/stable/reference/generated/numpy.diag.html#numpy.diag) define properties of special matrices represented as 2D arrays.


- Create a 2-D array called *TwoD_identity_matrix* of shape (3,3) with ones on the main diagonal and zeros elsewhere using the function `numpy.eye`
- Create a 2-D array called *Upper_diagonal_identity_matrix* of shape (3,3) with ones on the first upper diagonal and zeros elsewhere using the function `numpy.eye`
- Create a 2-D array called *Lower_diagonal_identity_matrix* of shape (3,3) with ones on the first lower diagonal and zeros elsewhere using the function `numpy.eye`
- Create an array called *Diagonal_element_of_matrix3* containing the main diagonal elements of matrix_3 using the function `numpy.diag`
- Create an array called *Upper_Diagonal_element_of_matrix3* containing the first upper diagonal elements of matrix_3 using the function `numpy.diag`
- Create an array called *Lower_Diagonal_element_of_matrix3* containing the first lower diagonal elements of matrix_3 using the function `numpy.diag`
- Create an array called *New_Diagonal_of_matrix3* with the main diagonal elements of matrix_3 on the main diagonal and zeros elsewhere using the function `numpy.diag`
- After doing that print all matrices together with their **dimension** and their **shape**.
    

In [135]:

TwoD_identity_matrix=np.eye(3)
print("The 2-D identity matrix of shape (3,3) is :\n", TwoD_identity_matrix)
print("The dimension of the 2-D identity matrix is :", TwoD_identity_matrix.ndim, "and its shape is :", TwoD_identity_matrix.shape)

Upper_diagonal_identity_matrix=np.eye(3, k=1)
print("The 2-D first upper diagonal identity matrix of shape (3,3) is :\n", Upper_diagonal_identity_matrix)
print("The dimension of 2-D first upper diagonal identity matrix is :", Upper_diagonal_identity_matrix.ndim, "and its shape is :", Upper_diagonal_identity_matrix.shape)

Lower_diagonal_identity_matrix=np.eye(3, k=-1)
print("The 2-D first lower diagonal identity matrix of shape (3,3) is :\n", Lower_diagonal_identity_matrix)
print("The dimension of 2-D first lower diagonal identity matrix is :", Lower_diagonal_identity_matrix.ndim, "and its shape is :", Lower_diagonal_identity_matrix.shape)

print("The matrix 3 is: \n", matrix_3)
Diagonal_element_of_matrix3=np.diag(matrix_3)
print("The diagonal elements of matrix 3 are :\n", Diagonal_element_of_matrix3)
print("The array with the diagonal elements of matrix 3 is of dimension :", Diagonal_element_of_matrix3.ndim, "and its shape is :", Diagonal_element_of_matrix3.shape)

Upper_Diagonal_element_of_matrix3=np.diag(matrix_3, k=1)
print("The array with the first upper diagonal elements of matrix_3 is :\n", Upper_Diagonal_element_of_matrix3)
print("The array with the first upper diagonal elements of matrix_3 is of dimension :", Upper_Diagonal_element_of_matrix3.ndim, "and its shape is :", Upper_Diagonal_element_of_matrix3.shape)

Lower_Diagonal_element_of_matrix3=np.diag(matrix_3, k=-1)
print("The array with the first lower diagonal elements of matrix_3 is :\n", Lower_Diagonal_element_of_matrix3)
print("The array with the first lower diagonal elements of matrix_3 is of dimension :", Lower_Diagonal_element_of_matrix3.ndim, "and its shape is :", Lower_Diagonal_element_of_matrix3.shape)

New_Diagonal_of_matrix3=np.diag(Diagonal_element_of_matrix3)
print("The New Diagonal matrix with the main diagonal elements of matrix_3 on the main diagonal and zeros elsewhere is :\n", New_Diagonal_of_matrix3)
print("The New Diagonal matrix is of dimension :", New_Diagonal_of_matrix3.ndim, "and its shape is :", New_Diagonal_of_matrix3.shape)


The 2-D identity matrix of shape (3,3) is :
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
The dimension of the 2-D identity matrix is : 2 and its shape is : (3, 3)
The 2-D first upper diagonal identity matrix of shape (3,3) is :
 [[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
The dimension of 2-D first upper diagonal identity matrix is : 2 and its shape is : (3, 3)
The 2-D first lower diagonal identity matrix of shape (3,3) is :
 [[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]
The dimension of 2-D first lower diagonal identity matrix is : 2 and its shape is : (3, 3)
The matrix 3 is: 
 [[ 1.+0.j  2.+0.j -1.+0.j]
 [ 5.+0.j  1.+0.j  3.+0.j]
 [ 1.+1.j  3.+0.j -1.+2.j]]
The diagonal elements of matrix 3 are :
 [ 1.+0.j  1.+0.j -1.+2.j]
The array with the diagonal elements of matrix 3 is of dimension : 1 and its shape is : (3,)
The array with the first upper diagonal elements of matrix_3 is :
 [2.+0.j 3.+0.j]
The array with the first upper diagonal elements of matrix_3 is of dimension : 1 and its shape is : (2,)
The arr

#### <center> c. <u>  General ndarray creation functions</u></center>
The ndarray creation functions e.g. [numpy.ones](https://numpy.org/doc/stable/reference/generated/numpy.ones.html#numpy.ones),  [numpy.zeros](https://numpy.org/doc/stable/reference/generated/numpy.zeros.html#numpy.zeros), and [random](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.random.html#numpy.random.Generator.random) define arrays based upon the desired shape. The ndarray creation functions can create arrays with any dimension by specifying how many dimensions and length along that dimension in a tuple or list.


- Create a 1-D array called *OneD_full_of_ones* of shape (5,) using the function `numpy.ones`
- Create a 2-D array called *TwoD_full_of_ones* of shape (5,3) using the function `numpy.ones`
- Create a 3-D array called *ThreeD_full_of_ones* of shape (5,3,2) using the function `numpy.ones`

- Create a 1-D array called *OneD_full_of_zeros* of shape (5,) using the function `numpy.zeros`
- Create a 2-D array called *TwoD_full_of_zeros* of shape (5,3) using the function `numpy.zeros`
- Create a 3-D array called *ThreeD_full_of_zeros* of shape (5,3,2) using the function `numpy.zeros`

- Create a 1-D array called *OneD_Random_between_zero_and_one* of shape (5,) using the function `numpy.random` and `default_rng`
- Create a 2-D array called *TwoD_Random_between_zero_and_one* of shape (5,3) using the function `numpy.random` and `default_rng`
- Create a 3-D array called *ThreeD_Random_between_zero_and_one* of shape (5,3,2) using the function `numpy.random` and `default_rng`

- After doing that print all arrays together with their **dimension** and their **shape**.


In [136]:
OneD_full_of_ones=np.ones((5,))
print("The 1-D array of shape (5,) and filled with 1 values  :\n", OneD_full_of_ones)
print("The dimension of the 1-D array of shape (5,) and filled with 1 values is :", OneD_full_of_ones.ndim, "and its shape is :", OneD_full_of_ones.shape)

TwoD_full_of_ones=np.ones((5,3))
print("The 2-D array of shape (5,3) and filled with 1 values  :\n", TwoD_full_of_ones)
print("The dimension of the 2-D array of shape (5,3) and filled with 1 values is :", TwoD_full_of_ones.ndim, "and its shape is :", TwoD_full_of_ones.shape)

ThreeD_full_of_ones=np.ones((5,3,2))
print("The 3-D array of shape (5,3,2) and filled with 1 values  :\n", ThreeD_full_of_ones)
print("The dimension of the 3-D array of shape (5,3,2) and filled with 1 values is :", ThreeD_full_of_ones.ndim, "and its shape is :", ThreeD_full_of_ones.shape)

OneD_full_of_zeros=np.zeros((5,))
print("The 1-D array of shape (5,) and filled with 0 values  :\n", OneD_full_of_zeros)
print("The dimension of the 1-D array of shape (5,) and filled with 0 values is :", OneD_full_of_zeros.ndim, "and its shape is :", OneD_full_of_zeros.shape)

TwoD_full_of_zeros=np.zeros((5,3))
print("The 2-D array of shape (5,3) and filled with 0 values  :\n", TwoD_full_of_zeros)
print("The dimension of the 2-D array of shape (5,3) and filled with 0 values is :", TwoD_full_of_zeros.ndim, "and its shape is :", TwoD_full_of_zeros.shape)

ThreeD_full_of_zeros=np.zeros((5,3,2))
print("The 3-D array of shape (5,3,2) and filled with 0 values  :\n", ThreeD_full_of_zeros)
print("The dimension of the 3-D array of shape (5,3,2) and filled with 0 values is :", ThreeD_full_of_zeros.ndim, "and its shape is :", ThreeD_full_of_zeros.shape)

from numpy.random import default_rng

OneD_Random_between_zero_and_one= default_rng(42).random((5,))

print("The 1-D array of shape (5,) and filled with random numbers between 0 and 1  :\n", OneD_full_of_zeros)
print("The dimension of the 1-D array of shape (5,) and filled with random numbers between 0 and 1 is :", OneD_full_of_zeros.ndim, "and its shape is :", OneD_full_of_zeros.shape)

TwoD_Random_between_zero_and_one= default_rng(42).random((5,3))

print("The 2-D array of shape (5,3) and filled with random numbers between 0 and 1  :\n", TwoD_Random_between_zero_and_one)
print("The dimension of the 2-D array of shape (5,3) and filled with random numbers between 0 and 1 is :", TwoD_Random_between_zero_and_one.ndim, "and its shape is :", TwoD_Random_between_zero_and_one.shape)

ThreeD_Random_between_zero_and_one= default_rng(42).random((5,3,2))

print("The 3-D array of shape (5,3,2) and filled with random numbers between 0 and 1  :\n", ThreeD_Random_between_zero_and_one)
print("The dimension of the 3-D array of shape (5,3,2) and filled with random numbers between 0 and 1 is :", ThreeD_Random_between_zero_and_one.ndim, "and its shape is :", ThreeD_Random_between_zero_and_one.shape)


OneD_full_of_ones = np.ones((5,))
TwoD_full_of_ones = np.ones((2, 3))
print(OneD_full_of_zeros)
print(TwoD_full_of_zeros)
print(OneD_full_of_ones)
print(TwoD_full_of_ones)
# Create an empty array with 2 elements
# creates an array whose initial content is random and depends on the state of the memory.
OneD_empty=np.empty(2) 
print(OneD_empty)
TwoD_empty=np.empty((6,4)) 
print(TwoD_empty)
a = np.ones((2, 3), dtype=np.int16)
print(a)

OneD_full_of_any_fill_value = np.full((4,), 88)
TwoD_full_of_any_fill_value= np.full((4,3), 6)
ThreeD_full_of_any_fill_value= np.full((4,3,2), 5)

print(OneD_full_of_any_fill_value)
print(TwoD_full_of_any_fill_value)
print(ThreeD_full_of_any_fill_value)

#np.eye()
TwoD_identity_matrix=np.eye(4)
print(OneD_identity_matrix)
#np.random.randn(shape)

The 1-D array of shape (5,) and filled with 1 values  :
 [1. 1. 1. 1. 1.]
The dimension of the 1-D array of shape (5,) and filled with 1 values is : 1 and its shape is : (5,)
The 2-D array of shape (5,3) and filled with 1 values  :
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
The dimension of the 2-D array of shape (5,3) and filled with 1 values is : 2 and its shape is : (5, 3)
The 3-D array of shape (5,3,2) and filled with 1 values  :
 [[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]
The dimension of the 3-D array of shape (5,3,2) and filled with 1 values is : 3 and its shape is : (5, 3, 2)
The 1-D array of shape (5,) and filled with 0 values  :
 [0. 0. 0. 0. 0.]
The dimension of the 1-D array of shape (5,) and filled with 0 values is : 1 and its shape is : (5,)
The 2-D array of shape (5,3) and filled with 0 values  :
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0.

## III. Exercise 3: Basic operations with arrays

In this exercise we are going to learn how to do the basics operations with arrays. Look into the documention for help.

To do the calculations, we are going to reuse the numpy elements we created before.


### 1. Calculation on scalars
Add up, subtract, multiply and divide *scalar_1* and *scalar_2*. Only use numpy functions.

In [137]:
#Addition
scalar_add = np.add(scalar_1, scalar_2)
print("Addition :",scalar_add)

#Substraction
scalar_sub = np.subtract(scalar_1, scalar_2) 
print("Substraction :",scalar_sub)

#Multiplication
scalar_mult = np.multiply(scalar_1, scalar_2)
print("Multiplication :",scalar_mult)

#Division
scalar_div = np.divide(scalar_1, scalar_2)
print("Division :",scalar_div)

Addition : 15
Substraction : -1
Multiplication : 56
Division : 0.875


### 2. Calculation on vectors
Do the same for the vectors :
Add up, subtract, multiply and divide vector_1 and vector_2. Only use numpy functions.

In [138]:
#TO DO
print("Vector 1 :",vector_1,"Vector 2 :",vector_2)

#Addition
vector_add = np.add(vector_1, vector_2) 
print("Addition :",vector_add)

#Substraction
vector_sub = np.subtract(vector_1, vector_2) 
print("Substraction :",vector_sub)

#Multiplication
vector_mult = np.multiply(vector_1, vector_2) 
print("Multiplication :",vector_mult)

#Division
vector_div = np.divide(vector_1, vector_2) 
print("Division :",vector_div)

Vector 1 : [1 2 3] Vector 2 : [3 2 1]
Addition : [4 4 4]
Substraction : [-2  0  2]
Multiplication : [3 4 3]
Division : [0.33333333 1.         3.        ]


### 3. Calculation on matrices

For the matrix, compute the sum, the difference, the multiplication and the division of *New_Diagonal_of_matrix3* an *matrix_3* and also compute the transpose and the inverse of matrix_3. Only use numpy functions.

In [139]:
#TO DO
print("Matrix 3 :\n",matrix_3,"\n New Diagonal matrix from matrix 3  :\n",New_Diagonal_of_matrix3)

#Addition
matrix_add = np.add(New_Diagonal_of_matrix3,matrix_3)
print("Addition :\n",matrix_add)

#Substraction
matrix_sub = np.subtract(New_Diagonal_of_matrix3,matrix_3)
print("Substraction :\n",matrix_sub)

#Multiplication
matrix_mult = np.multiply(New_Diagonal_of_matrix3,matrix_3)
print("Multiplication :\n",matrix_mult)

#Division
matrix_div = np.divide(New_Diagonal_of_matrix3,matrix_3)
print("Division :\n",matrix_div)

Matrix 3 :
 [[ 1.+0.j  2.+0.j -1.+0.j]
 [ 5.+0.j  1.+0.j  3.+0.j]
 [ 1.+1.j  3.+0.j -1.+2.j]] 
 New Diagonal matrix from matrix 3  :
 [[ 1.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  1.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j -1.+2.j]]
Addition :
 [[ 2.+0.j  2.+0.j -1.+0.j]
 [ 5.+0.j  2.+0.j  3.+0.j]
 [ 1.+1.j  3.+0.j -2.+4.j]]
Substraction :
 [[ 0.+0.j -2.+0.j  1.+0.j]
 [-5.+0.j  0.+0.j -3.+0.j]
 [-1.-1.j -3.+0.j  0.+0.j]]
Multiplication :
 [[ 1.+0.j  0.+0.j -0.+0.j]
 [ 0.+0.j  1.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j -3.-4.j]]
Division :
 [[ 1.+0.j  0.+0.j -0.-0.j]
 [ 0.+0.j  1.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  1.+0.j]]


In [140]:
#TO DO
#matrix_3=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Matrix 3 :\n",matrix_3)

#Transpose
matrix_tran = np.transpose(matrix_3)
print("Transpose : \n",matrix_tran)

#Inverse
matrix_inv = np.linalg.inv(matrix_3)
print("Inverse : \n",matrix_inv)

Matrix 3 :
 [[ 1.+0.j  2.+0.j -1.+0.j]
 [ 5.+0.j  1.+0.j  3.+0.j]
 [ 1.+1.j  3.+0.j -1.+2.j]]
Transpose : 
 [[ 1.+0.j  5.+0.j  1.+1.j]
 [ 2.+0.j  1.+0.j  3.+0.j]
 [-1.+0.j  3.+0.j -1.+2.j]]
Inverse : 
 [[ 0.31351351-0.68108108j  0.28108108+0.11351351j -0.3027027 +0.41621622j]
 [ 0.07027027+0.77837838j -0.17837838-0.12972973j  0.34594595-0.47567568j]
 [-0.54594595+0.87567568j -0.07567568-0.14594595j  0.38918919-0.53513514j]]


## Conclusion 
    In this first lab, you learnt to create different types of arrays and to perform basic arithmetic operations on them. You saw that arithmetic operators on arrays apply elementwise. A new array is created and filled with the result. Another important thing we have seen  that these arithmetic functions are working in the same way on each type of arrays and that there are also specific functions (for the matrices for example).